# Default values for day-01-anatomy.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: nginx
  tag: "1.25.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# This is a custom value we will use to test injection
customMessage: "Hello from Day 2 Values!"
