# Default values for day-01-anatomy.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: nginx
  tag: "1.25.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# This is a custom value we will use to test injection
customMessage: "Hello from Day 2 Values!"
# Day 4: Flow Control
# detailedConfig:
#   enabled: true
#   data:
#     color: blue

# Let's set a default to FALSE to prove it doesn't create by default.
enableConfigMap: false

# Day 5: Loops
# A list of strings
dbUsers:
  - "admin"
  - "reader"
  - "writer"

# A list of objects (key-value pairs)
environmentVars:
  - name: LOG_LEVEL
    value: "debug"
  - name: API_KEY
    value: "12345-secret"

# Day 7: Dependency Configuration
# This name 'redis' MUST match the name in Chart.yaml
redis:
  enabled: true  # This triggers the 'condition' we set in Chart.yaml

  # We are overriding the Bitnami Redis values here
  architecture: standalone
  auth:
    enabled: false  # Disable password for easier testing
  master:
    persistence:
      enabled: false # meaningful for testing so we don't need PVs
